/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Tickets controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, PagingResultTicketDto, CreateTicketRequestDto, TicketDto, TicketStatisticDto } from "../models";

@Injectable({ providedIn: "root" })
export class TicketsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    listTickets(page?: number, size?: number, sort?: Array<string>, observe?: 'body', options?: RequestOptions<'json'>): Observable<PagingResultTicketDto>;
    listTickets(page?: number, size?: number, sort?: Array<string>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PagingResultTicketDto>>;
    listTickets(page?: number, size?: number, sort?: Array<string>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PagingResultTicketDto>>;
    listTickets(page?: number, size?: number, sort?: Array<string>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/tickets`;

        let params = new HttpParams();
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (size != null) {
            params = HttpParamsBuilder.addToHttpParams(params, size, 'size');
        }
        if (sort != null) {
            params = HttpParamsBuilder.addToHttpParams(params, sort, 'sort');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    createTicket(createTicketRequestDto: CreateTicketRequestDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<TicketDto>;
    createTicket(createTicketRequestDto: CreateTicketRequestDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TicketDto>>;
    createTicket(createTicketRequestDto: CreateTicketRequestDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TicketDto>>;
    createTicket(createTicketRequestDto: CreateTicketRequestDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/tickets`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createTicketRequestDto, requestOptions);
    }

    getStatistics(observe?: 'body', options?: RequestOptions<'json'>): Observable<TicketStatisticDto>;
    getStatistics(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TicketStatisticDto>>;
    getStatistics(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TicketStatisticDto>>;
    getStatistics(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/tickets/statistics`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
