/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface ErrorDto {
    message: string;
}

export interface CreateTicketRequestDto {
    title: string;
    description: string;
}

export interface TicketDto {
    id: string | null;
    title: string;
    description: string;
    status: TicketStatus;
    createdAt: Date;
    updatedAt: Date;
}

export enum TicketStatus {
    OPEN = "OPEN",
    ASSIGNED = "ASSIGNED",
    INPROGRESS = "IN_PROGRESS",
    CLOSED = "CLOSED"
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
