spring.datasource.url=jdbc:postgresql://localhost:5432/open_ticket_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

springdoc.default-produces-media-type=application/json
